version: "3"
services:
  boot:
    image: p2p-auction
    environment:
      - MODE=boot
  node:
    image: p2p-auction
    depends_on:
      boot:
        condition: service_started
        restart: true
    environment:
      - MODE=main
    scale: 6

networks:
  default:
    driver: bridge
