version: "3"
services:
  boot:
    image: p2p-auction
    environment:
      - MODE=boot
    networks:
      - p2p-net
  node:
    image: p2p-auction
    depends_on:
      boot:
        condition: service_started
        restart: true
    environment:
      - MODE=main
    networks:
      - p2p-net
    scale: 6

networks:
  p2p-net:
    driver: bridge
